# Generated by Django 5.0.4 on 2026-05-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=500, verbose_name='Percorso')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data e ora')),
            ],
            options={
                'verbose_name': 'Visita pagina',
                'verbose_name_plural': 'Visite pagine (raw)',
                'ordering': ['-timestamp'],
            },
        ),
    ]
