# Generated by Django 5.0.4 on 2026-05-22 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageview',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Visita pagina', 'verbose_name_plural': 'Dashboard'},
        ),
    ]
