# Generated by Django 5.0.4 on 2026-04-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=255, verbose_name='Titolo')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug URL')),
                ('contenuto', models.TextField(verbose_name='Contenuto')),
                ('excerpt', models.TextField(blank=True, verbose_name='Riassunto')),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Immagine copertina')),
                ('pubblicato', models.BooleanField(default=False, verbose_name='Pubblicato')),
                ('data_pubblicazione', models.DateTimeField(blank=True, null=True, verbose_name='Data pubblicazione')),
                ('data_creazione', models.DateTimeField(auto_now_add=True, verbose_name='Data creazione')),
            ],
            options={
                'verbose_name': 'Articolo',
                'verbose_name_plural': 'Articoli',
                'ordering': ['-data_pubblicazione'],
            },
        ),
    ]
