# Generated by Django 5.0.4 on 2026-06-08 08:03

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='immagine_card',
            field=models.ImageField(blank=True, help_text='Miniatura della card nella lista degli articoli. Se vuota, viene usata la "Immagine copertina".', null=True, upload_to='blog/', verbose_name='Immagine card (lista blog)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='contenuto',
            field=tinymce.models.HTMLField(verbose_name='Contenuto'),
        ),
        migrations.AlterField(
            model_name='article',
            name='immagine',
            field=models.ImageField(blank=True, help_text='Banner mostrato in cima alla pagina del singolo articolo.', null=True, upload_to='blog/', verbose_name='Immagine copertina (pagina articolo)'),
        ),
    ]
