# Generated by Django 5.0.4 on 2026-04-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Telefono')),
                ('messaggio', models.TextField(verbose_name='Messaggio')),
                ('data_invio', models.DateTimeField(auto_now_add=True, verbose_name='Data invio')),
            ],
            options={
                'verbose_name': 'Richiesta contatto',
                'verbose_name_plural': 'Richieste contatto',
                'ordering': ['-data_invio'],
            },
        ),
        migrations.CreateModel(
            name='ValuationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Telefono')),
                ('indirizzo_immobile', models.CharField(max_length=255, verbose_name='Indirizzo immobile')),
                ('comune', models.CharField(max_length=100, verbose_name='Comune')),
                ('tipologia', models.CharField(max_length=100, verbose_name='Tipologia immobile')),
                ('mq', models.IntegerField(blank=True, null=True, verbose_name='MQ (opzionale)')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('data_invio', models.DateTimeField(auto_now_add=True, verbose_name='Data invio')),
            ],
            options={
                'verbose_name': 'Richiesta valutazione',
                'verbose_name_plural': 'Richieste valutazione',
                'ordering': ['-data_invio'],
            },
        ),
    ]
