# Generated by Django 5.0.4 on 2026-04-14 08:45

import apps.properties.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestionale_id', models.CharField(max_length=50, unique=True, verbose_name='ID gestionale')),
                ('codice_agenzia', models.CharField(blank=True, max_length=50, verbose_name='Codice agenzia')),
                ('titolo', models.CharField(max_length=255, verbose_name='Titolo')),
                ('descrizione', models.TextField(blank=True, verbose_name='Descrizione')),
                ('abstract', models.TextField(blank=True, verbose_name='Descrizione breve')),
                ('prezzo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prezzo (€)')),
                ('mq', models.IntegerField(blank=True, null=True, verbose_name='MQ')),
                ('tipologia', models.CharField(blank=True, max_length=100, verbose_name='Tipologia')),
                ('categoria_id', models.IntegerField(blank=True, null=True, verbose_name='ID categoria')),
                ('contratto', models.CharField(blank=True, choices=[('vendita', 'Vendita'), ('affitto', 'Affitto')], max_length=20, verbose_name='Contratto')),
                ('indirizzo', models.CharField(blank=True, max_length=255, verbose_name='Indirizzo')),
                ('comune', models.CharField(blank=True, max_length=100, verbose_name='Comune')),
                ('provincia', models.CharField(blank=True, max_length=10, verbose_name='Provincia')),
                ('zona', models.CharField(blank=True, max_length=100, verbose_name='Zona')),
                ('latitudine', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitudine', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('codice_istat', models.CharField(blank=True, max_length=20, verbose_name='Codice ISTAT')),
                ('bagni', models.IntegerField(blank=True, null=True, verbose_name='Bagni')),
                ('camere', models.IntegerField(blank=True, null=True, verbose_name='Camere')),
                ('locali', models.IntegerField(blank=True, null=True, verbose_name='Locali')),
                ('piano', models.CharField(blank=True, max_length=50, verbose_name='Piano')),
                ('ascensore', models.BooleanField(default=False, verbose_name='Ascensore')),
                ('garage', models.BooleanField(default=False, verbose_name='Garage')),
                ('riscaldamento', models.CharField(blank=True, max_length=100, verbose_name='Riscaldamento')),
                ('classe_energetica', models.CharField(blank=True, max_length=10, verbose_name='Classe energetica')),
                ('in_vetrina', models.BooleanField(default=False, verbose_name='In vetrina')),
                ('in_carosello', models.BooleanField(default=False, verbose_name='In carosello')),
                ('flag_storico', models.BooleanField(default=False, verbose_name='Storico (non pubblicare)')),
                ('data_creazione', models.DateTimeField(auto_now_add=True, verbose_name='Data creazione')),
                ('data_aggiornamento', models.DateTimeField(auto_now=True, verbose_name='Ultimo aggiornamento')),
                ('ultimo_sync', models.DateTimeField(blank=True, null=True, verbose_name='Ultimo sync')),
            ],
            options={
                'verbose_name': 'Immobile',
                'verbose_name_plural': 'Immobili',
                'ordering': ['-data_aggiornamento'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Nome file')),
                ('file', models.ImageField(upload_to=apps.properties.models.property_image_path, verbose_name='File')),
                ('is_planimetria', models.BooleanField(default=False, verbose_name='È planimetria')),
                ('ordine', models.IntegerField(default=0, verbose_name='Ordine')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='Immobile')),
            ],
            options={
                'verbose_name': 'Immagine',
                'verbose_name_plural': 'Immagini',
                'ordering': ['ordine'],
            },
        ),
    ]
