# Generated by Django 5.0.4 on 2026-05-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='visualizzazioni',
            field=models.PositiveIntegerField(default=0, verbose_name='Visualizzazioni'),
        ),
    ]
