# Generated by Django 5.0.4 on 2026-05-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_visualizzazioni'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='URL Video (YouTube embed)'),
        ),
    ]
