# Generated by Django 5.0.4 on 2026-05-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='gestionale_id',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='ID gestionale'),
        ),
    ]
