# Generated by Django 5.0.4 on 2026-04-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_review_id', models.CharField(max_length=255, unique=True)),
                ('author_name', models.CharField(max_length=255)),
                ('profile_photo_url', models.URLField(blank=True)),
                ('rating', models.IntegerField()),
                ('text', models.TextField(blank=True)),
                ('time', models.DateTimeField(help_text='Data della recensione')),
                ('language', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recensione Google',
                'verbose_name_plural': 'Recensioni Google',
                'ordering': ['-time'],
            },
        ),
    ]
